name: Docker Image CI

on:
  push:
    branches: [ main ]
    inputs:
      name:
        description: 'Define name'     
        required: true
        default: 'Sebi'     

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --build-arg NAME=${{ github.event.inputs.name }}
