name: Docker Image CI

on:
  push:
    branches: [ "main", "master" ]    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build . --build-arg NAME=Sebi -t myimage
    - name: Run Docker image
      run: |
        docker run --env NAME=Sebi myimage
    - name: Login
      run: |
        docker login --username ${{secrets.DHNAME}} --password ${{secrets.PASSWORD}}
    - name: Push
      run: |
        docker push myimage
        
