name: Docker Image CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Define name'     
        required: true
        default: 'Sebi'     

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Print arg
      run: echo "${{ github.event.inputs.name }}"
    - name: Build the Docker image
      run: "docker build . --file Dockerfile --build-arg NAME=${{ github.event.inputs.environment }}"
