on: 
  workflow_dispatch:
    inputs:
      name:
        description: 'Define name'     
        required: true
        default: 'Sebi'     
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Env: ${{ github.event.inputs.name }}"
